# create a new file named local.yaml to edit
# for more details, see https://github.com/node-config/node-config/wiki/Configuration-Files

# port to start the http and websocket server on
port: 3498

# if the password is not blank nodes will have to use the same password in their config to connect
password: ""

# set to true if the web client should show the about page
webShowAbout: false

# 0 for automatic  1 for light  2 for dark
webDefaultTheme: 0

# set to true if web clients should not animate charts
webDisableAnimation: false

# extra links to display in the nav bar
# when internal is true it can be used to link to a specific node with a link like /node/computer-id
# to remove all links put   extraNavLinks: []  into local.yaml
extraNavLinks:
  - name: "Github"
    link: "https://github.com/ScuffedSpaghetti/RTSysMon"
    internal: false